"""
Reference epidemiological data for non-COVID diseases.

When live WHO GHO / IHME APIs return sparse annual data (< 12 points),
this module provides historically-grounded synthetic daily/monthly series
based on published WHO and CDC estimates. The series are generated by
interpolating known annual burden figures into smooth monthly or weekly
time-series so the charts render correctly.

Sources used to shape the curves:
  - WHO Global Health Observatory annual counts
  - CDC / ECDC surveillance summaries
  - IHME Global Burden of Disease 2019 estimates
"""

from __future__ import annotations

import random
from datetime import date
from typing import Any, Dict, List, Optional, Tuple


# ---------------------------------------------------------------------------
# Annual reference anchors (global totals, approx.)
# Format: {year: (cases, deaths)}
# ---------------------------------------------------------------------------

GLOBAL_ANCHORS: Dict[str, Dict[int, Tuple[int, int]]] = {
    "influenza": {
        2000: (1_000_000_000, 650_000),
        2005: (1_100_000_000, 700_000),
        2009: (1_400_000_000, 500_000),   # H1N1 pandemic
        2010: (1_050_000_000, 650_000),
        2015: (1_100_000_000, 646_000),
        2018: (1_100_000_000, 650_000),
        2019: (1_100_000_000, 650_000),
        2020: (600_000_000, 390_000),     # non-covid flu suppressed
        2021: (500_000_000, 320_000),
        2022: (900_000_000, 580_000),
        2023: (1_050_000_000, 650_000),
        2024: (1_100_000_000, 650_000),
    },
    "dengue": {
        2000: (50_000_000, 25_000),
        2005: (60_000_000, 28_000),
        2010: (100_000_000, 40_000),
        2013: (390_000_000, 20_000),      # big estimate revision
        2015: (400_000_000, 22_000),
        2019: (421_000_000, 40_000),      # record year
        2020: (280_000_000, 19_000),
        2021: (300_000_000, 20_000),
        2022: (380_000_000, 30_000),
        2023: (500_000_000, 40_000),
        2024: (520_000_000, 42_000),
    },
    "malaria": {
        2000: (262_000_000, 900_000),
        2005: (255_000_000, 830_000),
        2010: (239_000_000, 660_000),
        2015: (214_000_000, 438_000),
        2020: (241_000_000, 627_000),     # COVID disruption spike
        2021: (247_000_000, 619_000),
        2022: (249_000_000, 608_000),
        2023: (263_000_000, 597_000),
        2024: (265_000_000, 590_000),
    },
    "tuberculosis": {
        2000: (8_300_000, 1_800_000),
        2005: (8_800_000, 1_700_000),
        2010: (8_800_000, 1_500_000),
        2015: (10_400_000, 1_800_000),
        2019: (10_000_000, 1_400_000),
        2020: (9_900_000, 1_500_000),
        2021: (10_600_000, 1_600_000),
        2022: (7_500_000, 1_300_000),
        2023: (8_000_000, 1_250_000),
        2024: (8_200_000, 1_200_000),
    },
    "measles": {
        2000: (30_000_000, 562_000),
        2005: (20_000_000, 311_000),
        2010: (12_000_000, 139_000),
        2015: (7_000_000, 73_000),
        2018: (9_800_000, 140_000),
        2019: (9_700_000, 207_500),       # outbreak spike
        2020: (7_500_000, 90_000),
        2021: (9_000_000, 128_000),
        2022: (8_700_000, 136_000),
        2023: (10_000_000, 107_000),
        2024: (9_500_000, 110_000),
    },
    "cholera": {
        2000: (137_000, 5_000),
        2005: (131_000, 2_200),
        2010: (317_000, 7_500),           # Haiti outbreak
        2015: (172_000, 1_300),
        2019: (923_000, 1_900),
        2020: (498_000, 3_900),
        2021: (223_000, 1_500),
        2022: (473_000, 2_300),
        2023: (700_000, 4_000),
        2024: (600_000, 3_500),
    },
    "hiv/aids": {
        2000: (5_300_000, 1_500_000),
        2005: (2_500_000, 2_000_000),
        2010: (1_800_000, 1_200_000),
        2015: (2_100_000, 1_100_000),
        2019: (1_700_000, 690_000),
        2020: (1_500_000, 680_000),
        2021: (1_500_000, 650_000),
        2022: (1_300_000, 630_000),
        2023: (1_300_000, 630_000),
        2024: (1_300_000, 620_000),
    },
    "ebola": {
        2000: (400, 300),
        2005: (12, 10),
        2010: (300, 150),
        2014: (28_600, 11_300),           # West Africa epidemic
        2015: (26_000, 10_800),
        2016: (250, 100),
        2017: (8, 4),
        2018: (3_400, 2_200),             # DRC outbreak
        2019: (3_400, 2_200),
        2020: (130, 55),
        2021: (12, 6),
        2022: (142, 55),
        2023: (5, 2),
        2024: (5, 2),
    },
    "hepatitis b": {
        2000: (6_000_000, 887_000),
        2005: (5_000_000, 850_000),
        2010: (4_000_000, 780_000),
        2015: (3_000_000, 887_000),
        2019: (1_500_000, 820_000),
        2020: (1_500_000, 820_000),
        2021: (1_500_000, 820_000),
        2022: (1_500_000, 820_000),
        2023: (1_500_000, 820_000),
        2024: (1_500_000, 820_000),
    },
    "polio": {
        2000: (719, 0),
        2005: (1_948, 0),
        2010: (1_352, 0),
        2015: (74, 0),
        2018: (33, 0),
        2019: (176, 0),
        2020: (1_226, 0),
        2021: (682, 0),
        2022: (1_229, 0),
        2023: (997, 0),
        2024: (730, 0),
    },
    "yellow fever": {
        2000: (200_000, 30_000),
        2005: (200_000, 30_000),
        2010: (84_000, 29_000),
        2015: (84_000, 29_000),
        2016: (7_000, 400),
        2019: (7_000, 400),
        2020: (7_000, 400),
        2021: (7_000, 400),
        2022: (7_000, 400),
        2023: (9_000, 450),
        2024: (10_000, 500),
    },
    "zika": {
        2014: (5_000, 0),
        2015: (440_000, 0),               # Americas outbreak
        2016: (500_000, 0),
        2017: (50_000, 0),
        2018: (20_000, 0),
        2019: (25_000, 0),
        2020: (15_000, 0),
        2021: (15_000, 0),
        2022: (30_000, 0),
        2023: (35_000, 0),
        2024: (30_000, 0),
    },
}

# Country scaling factors relative to global (approximate burden share).
COUNTRY_SCALE: Dict[str, Dict[str, float]] = {
    "India": {
        "influenza": 0.18, "dengue": 0.12, "malaria": 0.04,
        "tuberculosis": 0.28, "measles": 0.15, "cholera": 0.02,
        "hiv/aids": 0.02, "ebola": 0.01, "hepatitis b": 0.11,
        "polio": 0.01, "yellow fever": 0.01, "zika": 0.01,
    },
    "China": {
        "influenza": 0.22, "dengue": 0.04, "malaria": 0.01,
        "tuberculosis": 0.09, "measles": 0.05, "cholera": 0.01,
        "hiv/aids": 0.011, "ebola": 0.01, "hepatitis b": 0.29,
        "polio": 0.01, "yellow fever": 0.01, "zika": 0.01,
    },
    "United States": {
        "influenza": 0.04, "dengue": 0.01, "malaria": 0.01,
        "tuberculosis": 0.003, "measles": 0.002, "cholera": 0.01,
        "hiv/aids": 0.02, "ebola": 0.01, "hepatitis b": 0.012,
        "polio": 0.01, "yellow fever": 0.01, "zika": 0.01,
    },
    "Brazil": {
        "influenza": 0.05, "dengue": 0.12, "malaria": 0.01,
        "tuberculosis": 0.025, "measles": 0.01, "cholera": 0.01,
        "hiv/aids": 0.014, "ebola": 0.01, "hepatitis b": 0.015,
        "polio": 0.01, "yellow fever": 0.003, "zika": 0.12,
    },
    "Nigeria": {
        "influenza": 0.03, "dengue": 0.01, "malaria": 0.27,
        "tuberculosis": 0.05, "measles": 0.08, "cholera": 0.15,
        "hiv/aids": 0.09, "ebola": 0.02, "hepatitis b": 0.05,
        "polio": 0.15, "yellow fever": 0.08, "zika": 0.01,
    },
    "South Africa": {
        "influenza": 0.015, "dengue": 0.01, "malaria": 0.01,
        "tuberculosis": 0.038, "measles": 0.005, "cholera": 0.002,
        "hiv/aids": 0.17, "ebola": 0.01, "hepatitis b": 0.02,
        "polio": 0.01, "yellow fever": 0.01, "zika": 0.01,
    },
    "Indonesia": {
        "influenza": 0.06, "dengue": 0.09, "malaria": 0.015,
        "tuberculosis": 0.085, "measles": 0.04, "cholera": 0.02,
        "hiv/aids": 0.007, "ebola": 0.01, "hepatitis b": 0.07,
        "polio": 0.01, "yellow fever": 0.01, "zika": 0.01,
    },
    "Pakistan": {
        "influenza": 0.05, "dengue": 0.02, "malaria": 0.015,
        "tuberculosis": 0.06, "measles": 0.04, "cholera": 0.01,
        "hiv/aids": 0.003, "ebola": 0.01, "hepatitis b": 0.07,
        "polio": 0.08, "yellow fever": 0.01, "zika": 0.01,
    },
    "Global": {
        "influenza": 1.0, "dengue": 1.0, "malaria": 1.0,
        "tuberculosis": 1.0, "measles": 1.0, "cholera": 1.0,
        "hiv/aids": 1.0, "ebola": 1.0, "hepatitis b": 1.0,
        "polio": 1.0, "yellow fever": 1.0, "zika": 1.0,
    },
}

# Default scale for countries not explicitly listed.
_DEFAULT_SCALE = 0.02


def _get_country_scale(country: str, disease: str) -> float:
    country_map = COUNTRY_SCALE.get(country)
    if country_map is None:
        # Try case-insensitive match.
        for k, v in COUNTRY_SCALE.items():
            if k.lower() == country.lower():
                country_map = v
                break
    if country_map is None:
        return _DEFAULT_SCALE
    return country_map.get(disease.lower(), _DEFAULT_SCALE)


def _lerp(a: float, b: float, t: float) -> float:
    return a + (b - a) * t


def _interpolate_annual(
    anchors: Dict[int, Tuple[int, int]],
    start_year: int,
    end_year: int,
) -> Dict[int, Tuple[float, float]]:
    """Linear interpolation between anchor years."""
    sorted_years = sorted(anchors.keys())
    result: Dict[int, Tuple[float, float]] = {}

    for year in range(start_year, end_year + 1):
        # Find surrounding anchors.
        prev_yr = max((y for y in sorted_years if y <= year), default=sorted_years[0])
        next_yr = min((y for y in sorted_years if y >= year), default=sorted_years[-1])
        if prev_yr == next_yr:
            result[year] = (float(anchors[prev_yr][0]), float(anchors[prev_yr][1]))
        else:
            t = (year - prev_yr) / (next_yr - prev_yr)
            c = _lerp(anchors[prev_yr][0], anchors[next_yr][0], t)
            d = _lerp(anchors[prev_yr][1], anchors[next_yr][1], t)
            result[year] = (c, d)

    return result


# Seasonality multipliers by month (index 0 = Jan) for select diseases.
MONTH_SEASONALITY: Dict[str, List[float]] = {
    "influenza": [1.5, 1.4, 1.1, 0.7, 0.5, 0.4, 0.4, 0.5, 0.7, 1.0, 1.3, 1.5],
    "dengue":    [0.8, 0.9, 1.1, 1.3, 1.4, 1.2, 1.0, 0.9, 0.9, 1.0, 1.1, 0.8],
    "malaria":   [0.7, 0.7, 0.8, 1.0, 1.3, 1.5, 1.6, 1.5, 1.3, 1.1, 0.9, 0.7],
    "measles":   [1.5, 1.6, 1.6, 1.4, 1.2, 0.8, 0.6, 0.5, 0.6, 0.8, 1.1, 1.3],
    "cholera":   [0.7, 0.7, 0.8, 1.1, 1.4, 1.6, 1.5, 1.4, 1.3, 1.0, 0.8, 0.7],
}
_FLAT_SEASONALITY = [1.0] * 12


def _get_seasonality(disease: str) -> List[float]:
    return MONTH_SEASONALITY.get(disease.lower(), _FLAT_SEASONALITY)


def generate_monthly_series(
    disease: str,
    country: str,
    start_date: Optional[date] = None,
    end_date: Optional[date] = None,
) -> List[Dict[str, Any]]:
    """
    Generate a monthly time-series for a disease/country combination
    using interpolated annual anchor data.

    Returns a list of {date, cases, deaths, source, is_cumulative} dicts
    where `is_cumulative` is False (monthly incidence counts).
    """
    anchors = GLOBAL_ANCHORS.get(disease.lower())
    if not anchors:
        return []

    scale = _get_country_scale(country, disease)
    if scale <= 0:
        return []

    anchor_years = sorted(anchors.keys())
    if start_date is None:
        start_date = date(anchor_years[0], 1, 1)
    if end_date is None:
        end_date = date.today()

    start_year = start_date.year
    end_year = end_date.year

    interp = _interpolate_annual(anchors, start_year, end_year)
    seasonality = _get_seasonality(disease)

    rng = random.Random(hash(disease + country) & 0xFFFF_FFFF)

    points: List[Dict[str, Any]] = []
    # Track cumulative totals for growth-rate computation.
    cum_cases = 0
    cum_deaths = 0

    current = date(start_year, 1, 1)
    while current <= end_date:
        year = current.year
        month = current.month

        annual_cases, annual_deaths = interp.get(year, (0.0, 0.0))
        monthly_base_cases = (annual_cases * scale) / 12.0
        monthly_base_deaths = (annual_deaths * scale) / 12.0

        # Apply seasonality.
        season_mul = seasonality[month - 1]
        raw_cases = monthly_base_cases * season_mul
        raw_deaths = monthly_base_deaths * season_mul

        # ±15 % random jitter for realism.
        jitter_c = 1.0 + rng.uniform(-0.15, 0.15)
        jitter_d = 1.0 + rng.uniform(-0.15, 0.15)

        monthly_cases = max(0, int(raw_cases * jitter_c))
        monthly_deaths = max(0, int(raw_deaths * jitter_d))

        # Accumulate.
        cum_cases += monthly_cases
        cum_deaths += monthly_deaths

        if current >= start_date:
            points.append({
                "date": current.isoformat(),
                "cases": monthly_cases,
                "deaths": monthly_deaths,
                "source": "reference_data",
                "is_cumulative": False,
            })

        # Advance by one month.
        if month == 12:
            current = date(year + 1, 1, 1)
        else:
            current = date(year, month + 1, 1)

    return points


def get_reference_series(
    disease: str,
    country: str,
) -> List[Dict[str, Any]]:
    """
    Public entry point: return the reference monthly series for a disease/country.
    Returns [] if no reference data is available for the disease.
    """
    return generate_monthly_series(disease, country)
